name: stack_overflow_clone
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Visual Elements
  cupertino_icons: ^1.0.2
  animate_do: ^2.1.0
  shimmer_animation: ^2.1.0+1
  flutter_svg: ^1.1.5
  async_button: ^1.0.0-beta.1+1
  flutter_slidable: ^2.0.0

  # State Management
  provider: ^6.0.3

  # Local Operations
  flutter_secure_storage: ^6.0.0

  # Network
  dio: ^4.0.6

  # Link
  url_launcher: ^6.1.6

  # Localizations
  flutter_localizations:
    sdk: flutter

  # Format
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
