name: stack_overflow_clone
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  animate_do: ^2.1.0
  async_button: ^1.0.0-beta.1+1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.5
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  provider: ^6.0.3
  shimmer_animation: ^2.1.0+1
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
